### ISSUE TITLE
Improve Radio

### ISSUE THREAD

**Issue by filrak** [SnowdogApps/alpaca-storybook#143]
For sfui we need radio buttons to accept content via slots to handle different types of content. It's a better approach anyway I believe.

Reference https://github.com/DivanteLtd/storefront-ui/issues/27

**Comment by szafran89** [comment]
thanks @filrak we'll do it tomorrow
Internal ticket [DEV-51709]

**Comment by szafran89** [comment]
Merged to develop #138
